### ISSUE TITLE
Dependency?

### ISSUE THREAD

**Issue by fhorlaville** [ripred/CPUVolt#1]
Hi - Thanks for this, looks very promising.

Two questions:
1. Will it work with boards having an on-board battery regulator circuit like the Wemos Lolin 32 Lite?
2. There seems to be a dependency on avr/io.h - would you mind indicating which library is needed?

Thanks again,

F.

**Comment by ripred** [comment]
Hi and thanks for your interest! Unfortunately this only works on Atmel architecture microprocessors so it doesn't work on the Espressif based ESP32's. I will update the readme to reflect that.
